### ISSUE TITLE
Not able to search

### ISSUE THREAD

**Issue by CyberMew** [KittyGiraudel/github-release-search#4]
I am trying to search for releases in the `react-navigation/react-navigation` repo: https://github.com/react-navigation/react-navigation/

➜ npm run fetch -- --repo react-navigation/react-navigation         

> github-release-search@0.1.0 fetch /Users/me/Desktop/github/github-release-search
> node src/commands/program.js fetch "--repo" "react-navigation/react-navigation"

➜ npm run search -- "react-navigation" -- --repo react-navigation/react-navigation

> github-release-search@0.1.0 search /Users/me/Desktop/github/github-release-search
> node src/commands/program.js search "react-navigation" "--" "--repo" "react-navigation/react-navigation"

{ [Error: ENOENT: no such file or directory, open '/Users/me/Desktop/github/github-release-search/.cache/react-navigation.react-navigation']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path:
   '/Users/me/Desktop/github/github-release-search/.cache/react-navigation.react-navigation' }

Does this mean that only personal projects are supported?

**Comment by KittyGiraudel** [comment]
Hello, and thank you for opening an issue. I double checked and did find an issue, which I fixed on master. You should be able to sync and try again. Also make sure you have a GitHub access token with repos rights in your `.env`, as described in the README. ;)
